export const HOME_LOADING = 'HOME_LOADING'
export const HOME_GET_USERS = 'HOME_GET_USERS'
export const HOME_ADD_USER = 'HOME_ADD_USER'
export const HOME_SHOW_ALERT = 'HOME_SHOW_ALERT'
export const HOME_HIDE_ALERT = 'HOME_HIDE_ALERT'

export const AUTH_AUTHORIZE = 'AUTH_AUTHORIZE'